name: Build and Release YTLitePlus

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        default: "17.5"
        required: true
        type: string
      decrypted_youtube_url:
        description: "Direct URL of the decrypted YouTube IPA"
        required: true
        default: ""
        type: string
      bundle_id:
        description: "Bundle Identifier"
        default: "com.google.ios.youtube"
        required: true
        type: string
      app_name:
        description: "App Name"
        default: "YouTube"
        required: true
        type: string
      upload_artifact:
        description: "Upload IPA as artifact"
        required: false
        default: true
        type: boolean
      catbox_upload:
        description: "Upload IPA to Catbox.moe"
        required: false
        default: false
        type: boolean
      create_release:
        description: "Create a draft GitHub release"
        required: false
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTLitePlus (iOS ${{ inputs.sdk_version }})
    runs-on: macos-13
    permissions:
      contents: write

    env:
      THEOS: ${{ github.workspace }}/theos
      SDK_VERSION: ${{ inputs.sdk_version }}
      DEPLOY_TARGET: 14.0

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          path: main
          submodules: recursive

      - name: Install dependencies
        run: brew install ldid dpkg make

      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: Cache & download iOS SDK
        id: sdk-cache
        uses: actions/cache@v4
        with:
          path: theos/sdks/iPhoneOS${{ env.SDK_VERSION }}.sdk
          key: ios-sdk-${{ env.SDK_VERSION }}
          restore-keys: ios-sdk-

      - name: Download iOS SDK if needed
        if: steps.sdk-cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 --filter=tree:0 --sparse https://github.com/aricloverALT/sdks.git sdks-temp
          cd sdks-temp
          git sparse-checkout set iPhoneOS${{ env.SDK_VERSION }}.sdk
          git checkout
          mv *.sdk $THEOS/sdks/
          cd ..
          rm -rf sdks-temp

      - name: Install theos-jailed
        uses: actions/checkout@v4
        with:
          repository: qnblackcat/theos-jailed
          path: theos-jailed
          submodules: recursive

      - name: Run theos-jailed install
        run: ./theos-jailed/install
        env:
          THEOS: ${{ env.THEOS }}

      - name: Set GNU Make in PATH
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Build and install libundirect
        run: |
          cd main
          git clone https://github.com/opa334/libundirect.git libundirect
          cd libundirect
          make clean || true
          make TARGET=iphone:latest:14.0 SDK_VERSION=${{ env.SDK_VERSION }} DEPLOYMENT_TARGET=${{ env.DEPLOY_TARGET }} ARCHS=arm64
          bash install_to_theos.sh
        env:
          THEOS: ${{ env.THEOS }}

      - name: Fetch and patch YouTube IPA
        run: |
          wget "${{ inputs.decrypted_youtube_url }}" -O youtube.ipa
          unzip -q youtube.ipa -d tmp
          /usr/libexec/PlistBuddy -c "Delete :UISupportedDevices" tmp/Payload/YouTube.app/Info.plist || true
          cp -R main/Extensions/*.appex tmp/Payload/YouTube.app/PlugIns || true
        env:
          THEOS: ${{ env.THEOS }}

      - name: Extract YouTube version
        id: yt_version
        run: |
          VER=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" tmp/Payload/YouTube.app/Info.plist)
          echo "YT_VERSION=$VER" >> $GITHUB_ENV

      - name: Replace Makefile placeholders
        run: |
          cd main
          sed -i '' "s/^BUNDLE_ID.*/BUNDLE_ID = ${{ inputs.bundle_id }}/" Makefile
          sed -i '' "s/^DISPLAY_NAME.*/DISPLAY_NAME = ${{ inputs.app_name }}/" Makefile
          sed -i '' "s/^PACKAGE_VERSION.*/PACKAGE_VERSION = $YT_VERSION-5.0.1/" Makefile
          sed -i '' "s/^export TARGET.*/export TARGET = iphone:clang:${{ env.SDK_VERSION }}:${{ env.DEPLOY_TARGET }}/" Makefile
          sed -i '' "s|^export SDK_PATH.*|export SDK_PATH = $(THEOS)/sdks/iPhoneOS${{ env.SDK_VERSION }}.sdk/|" Makefile
        env:
          THEOS: ${{ env.THEOS }}

      - name: Build tweak package
        run: |
          cd main
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1
          mv packages/*.ipa "YTLitePlus_${YT_VERSION}_5.0.1.ipa"

      - name: Upload IPA artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: YTLitePlus_${YT_VERSION}_5.0.1.ipa
          path: YTLitePlus_${YT_VERSION}_5.0.1.ipa

      - name: Upload to Catbox
        if: ${{ inputs.catbox_upload }}
        run: |
          RESPONSE=$(curl -F fileToUpload=@YTLitePlus_${YT_VERSION}_5.0.1.ipa https://catbox.moe/user/api.php)
          URL=$(echo $RESPONSE | grep -o 'https://files.catbox.moe/[^\"]*')
          echo "CATBOX_URL=$URL" >> $GITHUB_ENV

      - name: Create Draft GitHub Release
        if: ${{ inputs.create_release }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${YT_VERSION}-5.0.1
          name: YTLitePlus v${YT_VERSION}-5.0.1
          files: YTLitePlus_${YT_VERSION}_5.0.1.ipa
          draft: true
